[package]
name = "async_port_knocker"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio     = { version = "1", features = ["full"] }
clap      = { version = "4", features = ["derive"] }
futures   = "0.3"
hex       = "0.4"
rand      = "0.9.2"
thiserror = "2.0.12"